version: "3.1"

services:
  postgres:
    image: postgres:14
    container_name: quill_db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - quill_db:/var/lib/postgresql/data

  pg_admin:
    image: dpage/pgadmin4
    container_name: pg_admin
    ports:
      - "5000:80"
    env_file:
      - .env
    volumes:
      - pgadmin_quill_db:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  quill_db: {}
  pgadmin_quill_db: {}
